version: '2'

services:
  test-application:
    image: infracloudio/csvserver
    volumes:
      - ~/inputFile:/csvserver/inputdata
    ports:
      - 9393:9300

  prometheus:
    image: prom/prometheus:v2.22.0 
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
