global:
  scrape_interval:     15s 
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'CSV_Server'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['127.0.0.1:9300']
